---
title: "flat_outils.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(stringi)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# get_working_files

The goal of this function is to find all R files that can contains functions written in R language.

The result is a vector of strings giving all the path to these R files relatively to the directory path given as argument.

Path containing `library` are omitted. 
    
```{r function-get_working_files}
#' Trouver les fichiers de travail R
#' 
#' Cette fonction recherche tous les fichiers R susceptibles de contenir des définitions de fonction
#' 
#' @param path character giving the root searching path
#' @param recursive logical telling if the search shoud be recursive or not
#'
#' @return vector of strings consisting of relative paths to the working R files
#' 
#' @export
get_working_files <- function(path = ".", recursive = TRUE){
    
  fichiers <- list.files(path = path,
                         recursive = recursive,
                         pattern = "[.](R|[R|r|Q|q]md)$")
  
  resultat <- fichiers[!grepl("[/]library[/]", fichiers)]
  
  return(resultat)
  
}
```
  
```{r example-get_working_files}
get_working_files()
```
  
```{r tests-get_working_files}

working_files1 <- get_working_files()
working_files2 <- get_working_files(".")

test_that("get_working_files works", {
  expect_true(inherits(get_working_files, "function"))
  
  expect_equal(
    object = identical(working_files1, working_files2),
    expected = TRUE)

})
```
  
# get_function_names

The goal is to retrieve all user created function names in a string
    
```{r development-get_function_names}
# You can prepare the code of the get_function_names() function here
```
  
```{r function-get_function_names}
#' Trouver les noms de fonctions
#' 
#' Cette fonction recherche tous les noms de fonctions créées par l'utilisateur
#' 
#' @param file character Path to an R file (Rmd, qmd, R)
#' @importFrom stringi stri_match_all_regex
#' @return vector of strings containing user function names
#' 
#' @export
get_function_names <- function(file) {
  
  lines <- paste0(readLines(file), collapse = '\n')
  function_names <- stringi::stri_match_all_regex(
    str = lines,
    pattern = "([a-z|A-Z][a-z|A-Z|0-9|_]*?)[ ]+?[<][-][ ]+?function",
    omit_no_match = FALSE
  )[[1]][,2]
  
  return(function_names)
  
}
```
  
```{r example-get_function_names}
working_files <- get_working_files()
if (length(working_files) > 0) {
  get_function_names(get_working_files()[[1]])
}
```
  
```{r tests-get_function_names}
test_that("get_function_names works", {
  expect_true(inherits(get_function_names, "function")) 
})
```
  
```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_outils.Rmd", vignette_name = "outils")
```
