# WARNING - Generated by {fusen} from dev/flat_outils.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_function_names works", {
  expect_true(inherits(get_function_names, "function")) 
})
