# WARNING - Generated by {fusen} from dev/flat_outils.Rmd: do not edit by hand


working_files1 <- get_working_files()
working_files2 <- get_working_files(".")

test_that("get_working_files works", {
  expect_true(inherits(get_working_files, "function"))
  
  expect_equal(
    object = identical(working_files1, working_files2),
    expected = TRUE)

})
