# WARNING - Generated by {fusen} from dev/flat_outils.Rmd: do not edit by hand # nolint: line_length_linter.

#' Trouver les noms de fonctions
#' 
#' Cette fonction recherche tous les noms de fonctions créées par l'utilisateur
#' 
#' @param file character Path to an R file (Rmd, qmd, R)
#' @importFrom stringi stri_match_all_regex
#' @return vector of strings containing user function names
#' 
#' @export
#' @examples
#' working_files <- get_working_files()
#' if (length(working_files) > 0) {
#'   get_function_names(get_working_files()[[1]])
#' }
get_function_names <- function(file) {
  
  lines <- paste0(readLines(file), collapse = '\n')
  function_names <- stringi::stri_match_all_regex(
    str = lines,
    pattern = "([a-z|A-Z][a-z|A-Z|0-9|_]*?)[ ]+?[<][-][ ]+?function",
    omit_no_match = FALSE
  )[[1]][,2]
  
  return(function_names)
  
}
