# WARNING - Generated by {fusen} from dev/flat_outils.Rmd: do not edit by hand

#' Trouver les fichiers de travail R
#' 
#' Cette fonction recherche tous les fichiers R susceptibles de contenir des définitions de fonction
#' 
#' @param path character giving the root searching path
#' @param recursive logical telling if the search shoud be recursive or not
#'
#' @return vector of strings consisting of relative paths to the working R files
#' 
#' @export
#' @examples
#' get_working_files()
get_working_files <- function(path = ".", recursive = TRUE){
    
  fichiers <- list.files(path = path,
                         recursive = recursive,
                         pattern = "[.](R|[R|r|Q|q]md)$")
  
  resultat <- fichiers[!grepl("[/]library[/]", fichiers)]
  
  return(resultat)
  
}
