# WARNING - Generated by {fusen} from dev/flat_my_sql.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create PostgreSQL database connection
#' 
#' This function creates the connection to the PostgreSQL database 
#' @import RPostgres
#' @return S4 object PqConnection
#' 
#' @export
#' @examples
#' con <- my_con()
my_con <- function(){

  DB_HOSTNAME <- Sys.getenv("DB_HOSTNAME")
  DB_USER <- Sys.getenv("DB_USER")
  DB_PASSWORD <- Sys.getenv("DB_PASSWORD")
  DB_PORT <- Sys.getenv("DB_PORT")
  DB_NAME <- Sys.getenv("DB_NAME")

  con <- RPostgres::dbConnect(
    drv = RPostgres::Postgres(), 
    dbname = DB_NAME,
    host = DB_HOSTNAME,
    port = DB_PORT,
    user = DB_USER,
    password = DB_PASSWORD
  )

  return(con)
  
}

